#!/bin/sh

cd /app

echo 'Running isort'
isort .

echo 'Running autoflake'
autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --recursive .

echo 'Running autopep8'
find . -name '*.py' -exec autopep8 --in-place --aggressive --aggressive --max-line-length 90 {} \;
