version: "3.8"
services:
  juggertube-development:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    container_name: juggertube
    environment:
      FLASK_ENV: 'development'
      CACHE_REDIS_HOST: '0.0.0.0'
      CACHE_REDIS_PORT: '6379'
      DATABASE_URL: 'mysql+pymysql://user:password@localhost:3306/juggertube'
      MYSQL_DATABASE: 'juggertube'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      GENERATE_TEST_DATA: False
      RABBITMQ_WORKER_PASS: 'mypass'
      RABBITMQ_WORKER_USER: 'worker'
      RABBITMQ_BE_PASS: 'mypass'
      RABBITMQ_BE_USER: 'backend'
      SECRET_KEY: 'secret'
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
      - "127.0.0.1:3306:3306/tcp"
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:15672:15672/tcp"