openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/video-frontend/get-teams-overview:
    get:
      summary: Get teams overview
      description: Returns a list of all registered teams.
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: The unique ID of the team
                      example: 123
                      nullable: false
                    name:
                      type: string
                      description: The name of the team
                      example: "Berlin Bears"
                      nullable: false
                    city:
                      type: string
                      description: The city where the team is based
                      example: "Berlin"
                      nullable: false
                    country:
                      type: string
                      description: The country where the team is based
                      example: "Germany"
                      nullable: false

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error" 