openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/update-user-picture:
    put:
      summary: Update user picture
      operationId: updateUserPicture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserPictureRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '403':
          description: Unauthorized

        '404':
          description: User not Found

        '500':
          description: Internal Server Error

components:
  schemas:
    UpdateUserPictureRequestBody:
      type: object
      properties:
        picture:
          type: string
