openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/update-user-role:
    put:
      summary: Update user role
      operationId: updateUserRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRoleRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '403':
          description: Unauthorized

        '404':
          description: User not Found

        '500':
          description: Internal Server Error

components:
  schemas:
    UpdateUserRoleRequestBody:
      type: object
      properties:
        userId:
          type: integer
        role:
          type: string
          enum:
            - user
            - moderator
            - admin
