"""create users table

Revision ID: 14bc7f5ffa29
Revises: e6c47a645f30
Create Date: 2025-05-24 20:20:57.033012

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14bc7f5ffa29'
down_revision = 'e6c47a645f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'login_attempts',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'username',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'attempts',
            sa.Integer(),
            server_default='1',
            nullable=False),
        sa.Column(
            'last_attempt',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'users',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'username',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'escaped_username',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'password_hash',
            sa.String(
                length=255),
            nullable=False),
        sa.Column(
            'password_reset_hash',
            sa.String(
                length=255),
            nullable=True),
        sa.Column(
            'email',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'name',
            sa.String(
                length=100),
            nullable=True),
        sa.Column(
            'picture',
            sa.String(
                length=255),
            server_default='default.png',
            nullable=True),
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            server_default='0',
            nullable=False),
        sa.Column(
            'role',
            sa.Enum(
                'USER',
                'MODERATOR',
                'ADMIN',
                name='userroleenum'),
            server_default='user',
            nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
