"""Update indexes and constraints for various tables

Revision ID: 2c7d5b8bb675
Revises: f44c06b09c84
Create Date: 2025-06-27 08:40:57.422494

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7d5b8bb675'
down_revision = 'f44c06b09c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('jtr_link',
                              existing_type=mysql.VARCHAR(length=255),
                              nullable=True)
        batch_op.drop_index(batch_op.f('id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=255),
                              nullable=False,
                              existing_server_default=sa.text("'default.png'"))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('picture',
                              existing_type=mysql.VARCHAR(length=255),
                              nullable=True,
                              existing_server_default=sa.text("'default.png'"))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)
        batch_op.alter_column('jtr_link',
                              existing_type=mysql.VARCHAR(length=255),
                              nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    # ### end Alembic commands ###
