"""tournaments are unique through combination of name and start_date

Revision ID: e6c47a645f30
Revises: 16de9d54ae78
Create Date: 2025-05-15 10:40:06.487151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c47a645f30'
down_revision = '16de9d54ae78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['channel_link'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_tournament_name_date', ['name', 'start_date'])
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['jtr_link'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['video_link'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uix_tournament_name_date', type_='unique')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
