"""add video status

Revision ID: f44c06b09c84
Revises: 14bc7f5ffa29
Create Date: 2025-06-02 16:28:57.996998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f44c06b09c84'
down_revision = '14bc7f5ffa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.Enum(
                    'PENDING',
                    'APPROVED',
                    'DECLINED',
                    name='videostatusenum'),
                nullable=False))
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['uploader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploader_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
