openapi: 3.0.0
info:
  title: Video Frontend API
  version: 1.0.0
paths:
  /api/video-frontend/get-pending-video-overview:
    get:
      summary: Get pending videos
      description: Returns a list of all videos with status "pending".
      responses:
        '200':
          description: A list of pending videos
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: The unique ID of the video
                    example: 123
                    nullable: false
                  name:
                    type: string
                    description: The name of the video
                    example: "Tournament Highlights"
                    nullable: false
                  category:
                    type: string
                    description: The category of the video
                    example: "HIGHLIGHTS"
                  status:
                    type: string
                    description: The status of the video
                    example: "pending"

        '403':
          description: Access denied for non-privileged users
