### Get pending videos for user
GET https://{{host}}/api/video-frontend/get-pending-video-overview
Authorization: Bearer {{jwtToken}}

> {%
    client.test("It should return a successful status code for privileged users", function() {
        client.assert(response.status === 200 || response.status === 403, "Response status is neither 200 nor 403");
    });
%}
