export enum VideoFormModelFieldsEnum {
  NAME = 'name',
  VIDEO_LINK = 'videoLink',
  CHANNEL_ID = 'channelId',
  CHANNEL_NAME = 'channelName',
  CHANNEL_LINK = 'channelLink',
  CATEGORY = 'category',
  UPLOAD_DATE = 'uploadDate',
  DATE_OF_RECORDING = 'dateOfRecording',
  TOPIC = 'topic',
  GUESTS = 'guests',
  WEAPON_TYPE = 'weaponType',
  GAME_SYSTEM = 'gameSystem',
  TOURNAMENT_ID = 'tournamentId',
  TOURNAMENT_NAME = 'tournamentName',
  TOURNAMENT_CITY = 'tournamentCity',
  TOURNAMENT_START_DATE = 'tournamentStartDate',
  TOURNAMENT_END_DATE = 'tournamentEndDate',
  TEAM_ONE_ID = 'teamOneId',
  TEAM_ONE_NAME = 'teamOneName',
  TEAM_ONE_CITY = 'teamOneCity',
  TEAM_ONE_MIX = 'teamOneMix',
  TEAM_TWO_ID = 'teamTwoId',
  TEAM_TWO_NAME = 'teamTwoName',
  TEAM_TWO_CITY = 'teamTwoCity',
  TEAM_TWO_MIX = 'teamTwoMix',
  COMMENT = 'comment',
};