openapi: 3.0.0
info:
  title: Create Multiple Channels API
  version: 1.0.0
  description: API endpoint for creating multiple channels at once

paths:
  /api/channel-frontend/create-multiple-channels:
    post:
      summary: Create multiple channels
      description: Creates multiple channels in a single request
      operationId: createMultipleChannels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                channels:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Display name of the channel
                        example: "Jugger e. V."
                      channelIdentifier:
                        type: string
                        description: Either YouTube handle, full channel URL, or external URL
                        example: "@JuggereV"
                      linkType:
                        type: string
                        enum: [YOUTUBE_CUSTOM, YOUTUBE_CHANNEL, EXTERNAL]
                        description: Type of the channel link
                        example: "YOUTUBE_CUSTOM"
                    required:
                      - channelIdentifier
                      - linkType
              required:
                - channels
      responses:
        '200':
          description: All channels created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  created_channels:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: integer
                        channelLink:
                          type: string
                  failed_channels:
                    type: array
                    items:
                      type: object
                      properties:
                        identifier:
                          type: string
                        reason:
                          type: string
        '207':
          description: Some channels created successfully, others failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChannelsResponse'
        '400':
          description: Invalid request or no channels created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChannelsResponse'

components:
  schemas:
    CreateChannelsResponse:
      type: object
      properties:
        created_channels:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              id:
                type: integer
              channelLink:
                type: string
        failed_channels:
          type: array
          items:
            type: object
            properties:
              identifier:
                type: string
              reason:
                type: string 