openapi: 3.0.0
info:
  title: Create Multiple Channels API
  version: 1.0.0
  description: API endpoint for creating multiple channels at once

paths:
  /api/team-frontend/create-multiple-teams:
    post:
      summary: Create multiple channels
      description: Creates multiple channels in a single request
      operationId: createMultipleChannels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teams:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the channels
                        example: "Jugger Basilisken Basel"
                      channelLink:
                        type: string
                        description: Link to the Channel
                        example: "https://www.youtube.com/@juggerbasel"
                    required:
                      - name
                      - channelLink
              required:
                - teams
      responses:
        '200':
          description: All channels created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  created_teams:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: integer
                  failed_teams:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        reason:
                          type: string
        '207':
          description: Some channels created successfully, others failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  created_teams:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        id:
                          type: integer
                  failed_teams:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        reason:
                          type: string
        '400':
          description: Invalid request or no channels created
          content:
            application/json:
              schema:
                type: object
                properties:
                  created_teams:
                    type: array
                    items:
                      type: object
                  failed_teams:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        reason:
                          type: string 