openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/video-frontend/get-channel-overview:
    get:
      summary: Get channel overview
      description: Returns a list of all registered channels.
      responses:
        '200':
          description: A list of channels
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: The unique ID of the channel
                      example: 123
                      nullable: false
                    name:
                      type: string
                      description: The name of the channel
                      example: "Jugger Basel"
                      nullable: false
                    channelLink:
                      type: string
                      description: The link to the channel
                      example: "https://www.youtube.com/@juggerbasel"
                      nullable: false

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"